test : test.ico
	icon test.ico
p2_if : p2_if.ico
	icon p2_if.ico
p2_if_while : p2_if_while.ico
	icon p2_if_while.ico
p2_while : p2_while.ico
	icon p2_while.ico
p2_repeat : p2_repeat.ico
	icon p2_repeat.ico
p2_until : p2_until.ico
	icon p2_until.ico
p2_switch : p2_switch.ico
	icon p2_switch.ico